local spells = {
    { level = 1, points = 2, name = 'Foot Kick', type = 'Slashing', trait = 'Lizard Killer (4)' , mob_family = 'Rabbit' },
    { level = 1, points = 1, name = 'Pollen', type = 'Light-based', trait = 'Resist Sleep (4)' , mob_family = 'Bee' },
    { level = 1, points = 2, name = 'Sandspin', type = 'Earth-based', trait = 'None' , mob_family = 'Worm' },
    { level = 4, points = 1, name = 'Power Attack', type = 'Blunt', trait = 'Plantoid Killer (4)' , mob_family = 'Beetle' },
    { level = 4, points = 2, name = 'Sprout Smack', type = 'Blunt', trait = 'Beast Killer (4)' , mob_family = 'Sapling' },
    { level = 4, points = 3, name = 'Wild Oats', type = 'Piercing', trait = 'Beast Killer (4)' , mob_family = 'Mandragora' },
    { level = 8, points = 1, name = 'Cocoon', type = 'Earth-based', trait = 'None' , mob_family = 'Crawler' },
    { level = 8, points = 3, name = 'Metallic Body', type = 'Earth-based', trait = 'Conserve MP (4)' , mob_family = 'Crab' },
    { level = 8, points = 2, name = 'Queasyshroom', type = 'Ranged', trait = 'None' , mob_family = 'Funguar' },
    { level = 12, points = 3, name = 'Battle Dance', type = 'Slashing', trait = 'Attack Bonus (4)' , mob_family = 'Orc' },
    { level = 12, points = 3, name = 'Feather Storm', type = 'Ranged', trait = 'Rapid Shot (4)' , mob_family = 'Yagudo' },
    { level = 12, points = 3, name = 'Head Butt', type = 'Blunt', trait = 'None' , mob_family = 'Quadav' },
    { level = 16, points = 4, name = 'Healing Breeze', type = 'Wind-based', trait = 'Auto Regen (4)' , mob_family = 'Dhalmel' },
    { level = 16, points = 2, name = 'Helldive', type = 'Blunt', trait = 'None' , mob_family = 'Bird' },
    { level = 16, points = 2, name = 'Sheep Song', type = 'Light-based', trait = 'Auto Regen (4)' , mob_family = 'Sheep' },
    { level = 18, points = 2, name = 'Blastbomb', type = 'Fire-based', trait = 'Magic Atk. Bonus (4)' , mob_family = 'Warmachine' },
    { level = 18, points = 2, name = 'Bludgeon', type = 'Blunt', trait = 'Undead Killer (4)' , mob_family = 'Cardian' },
    { level = 18, points = 2, name = 'Cursed Sphere', type = 'Water-based', trait = 'Magic Atk. Bonus (4)' , mob_family = 'Fly' },
    { level = 20, points = 2, name = 'Blood Drain', type = 'Dark-based', trait = 'Conserve MP (4)' , mob_family = 'Giant Bat' },
    { level = 20, points = 2, name = 'Claw Cyclone', type = 'Slashing', trait = 'Lizard Killer (4)' , mob_family = 'Tiger' },
    { level = 22, points = 1, name = 'Poison Breath', type = 'Water-based', trait = 'Clear Mind (4)' , mob_family = 'Hound' },
    { level = 24, points = 4, name = 'Soporific', type = 'Dark-based', trait = 'Clear Mind (4)' , mob_family = 'Flytrap' },
    { level = 26, points = 3, name = 'Screwdriver', type = 'Piercing', trait = 'Evasion Bonus (4)' , mob_family = 'Pugil' },
    { level = 28, points = 4, name = 'Vanity Dive', type = 'Slashing', trait = 'Accuracy Bonus (4)' , mob_family = 'Wanderer (Promy)' },
    { level = 28, points = 3, name = 'Bomb Toss', type = 'Fire-based', trait = 'Magic Acc. Bonus (4)' , mob_family = 'Goblin' },
    { level = 30, points = 2, name = 'Grand Slam', type = 'Blunt', trait = 'Defense Bonus (4)' , mob_family = 'Gigas' },
    { level = 30, points = 3, name = 'Wild Carrot', type = 'Light-based', trait = 'Resist Sleep (4)' , mob_family = 'Rabbit' },
    { level = 32, points = 3, name = 'Empty Thrash', type = 'Slashing', trait = 'Max HP Boost (4)' , mob_family = 'Unknown (Promy)' },
    { level = 32, points = 2, name = 'Chaotic Eye', type = 'Wind-based', trait = 'Conserve MP (4)' , mob_family = 'Coeurl' },
    { level = 32, points = 1, name = 'Sound Blast', type = 'Fire-based', trait = 'Magic Atk. Bonus (4)' , mob_family = 'Cockatrice' },
    { level = 34, points = 2, name = 'Death Ray', type = 'Dark-based', trait = 'None' , mob_family = 'Hecteye' },
    { level = 34, points = 3, name = 'Smite of Rage', type = 'Slashing', trait = 'Undead Killer (4)' , mob_family = 'Evil Weapon' },
    { level = 36, points = 2, name = 'Digest', type = 'Dark-based', trait = 'Conserve MP (4)' , mob_family = 'Slime' },
    { level = 36, points = 2, name = 'Pinecone Bomb', type = 'Ranged', trait = 'None' , mob_family = 'Treant' },
    { level = 38, points = 3, name = 'Occultation', type = 'Wind-based', trait = 'Evasion Bonus (4)' , mob_family = 'Unknown (Promy)' },
    { level = 38, points = 2, name = 'Blank Gaze', type = 'Light-based', trait = 'Magic Atk. Bonus (4)' , mob_family = 'Opo-opo' },
    { level = 38, points = 4, name = 'Jet Stream', type = 'Blunt', trait = 'Rapid Shot (4)' , mob_family = 'Bat Trio' },
    { level = 38, points = 3, name = 'Uppercut', type = 'Blunt', trait = 'Attack Bonus (4)' , mob_family = 'Goobbue' },
    { level = 40, points = 4, name = 'Mysterious Light', type = 'Wind-based', trait = 'Max MP Boost (4)' , mob_family = 'Magic Pot' },
    { level = 40, points = 3, name = 'Terror Touch', type = 'Hand-to-Hand', trait = 'Defense Bonus (4)' , mob_family = 'Ghost' },
    { level = 42, points = 4, name = 'Auroral Drape', type = 'Wind-based', trait = 'Fast Cast (4)' , mob_family = 'Unknown (Promy)' },
    { level = 42, points = 4, name = 'MP Drainkiss', type = 'Dark-based', trait = 'None' , mob_family = 'Leech' },
    { level = 42, points = 3, name = 'Venom Shell', type = 'Water-based', trait = 'Clear Mind (4)' , mob_family = 'Uragnite' },
    { level = 44, points = 4, name = 'Blitzstrahl', type = 'Thunder-based', trait = 'Magic Acc. Bonus (4)' , mob_family = 'Dolls' },
    { level = 44, points = 2, name = 'Mandibular Bite', type = 'Slashing', trait = 'Plantoid Killer (4)' , mob_family = 'Antlion' },
    { level = 44, points = 2, name = 'Stinking Gas', type = 'Wind-based', trait = 'Auto Refresh (1)' , mob_family = 'Doomed' },
    { level = 46, points = 2, name = 'Awful Eye', type = 'Water-based', trait = 'Clear Mind (4)' , mob_family = 'Bugard' },
    { level = 46, points = 3, name = 'Geist Wall', type = 'Dark-based', trait = 'Auto Refresh (4)' , mob_family = 'Eft' },
    { level = 46, points = 3, name = 'Magnetite Cloud', type = 'Earth-based', trait = 'Magic Def. Bonus (4)' , mob_family = 'Antica' },
    { level = 48, points = 3, name = 'Blood Saber', type = 'Dark-based', trait = 'Auto Refresh (4)' , mob_family = 'Skeleton' },
    { level = 48, points = 4, name = 'Jettatura', type = 'Dark-based', trait = 'None' , mob_family = 'Hippogryph' },
    { level = 48, points = 4, name = 'Refueling', type = 'Wind-based', trait = 'None' , mob_family = 'Cluster' },
    { level = 48, points = 4, name = 'Sickle Slash', type = 'Hand-to-Hand', trait = 'Store TP (4)' , mob_family = 'Spider' },
    { level = 50, points = 3, name = 'Frightful Roar', type = 'Wind-based', trait = 'Auto Refresh (2)' , mob_family = 'Tauri' },
    { level = 50, points = 3, name = 'Ice Break', type = 'Ice-based', trait = 'Magic Def. Bonus (4)' , mob_family = 'Golem' },
    { level = 50, points = 3, name = 'Self-Destruct', type = 'Fire-based', trait = 'Auto Refresh (2)' , mob_family = 'Bomb' },
    { level = 52, points = 1, name = 'Cold Wave', type = 'Ice-based', trait = 'Auto Refresh (1)' , mob_family = 'Snoll' },
    { level = 52, points = 3, name = 'Filamented Hold', type = 'Earth-based', trait = 'Clear Mind (4)' , mob_family = 'Diremite' },
    { level = 54, points = 4, name = 'Quad. Continuum', type = 'Piercing', trait = 'Defense Bonus (4)' , mob_family = 'Empty (Promy)' },
    { level = 54, points = 3, name = 'Hecatomb Wave', type = 'Wind-based', trait = 'Max MP Boost (4)' , mob_family = 'Demon' },
    { level = 54, points = 4, name = 'Radiant Breath', type = 'Light-based', trait = 'None' , mob_family = 'Wyvern' },
    { level = 56, points = 4, name = 'Winds of Promy.', type = 'Light-based', trait = 'Auto Refresh (2)' , mob_family = 'Unknown (Promy)' },
    { level = 56, points = 2, name = 'Feather Barrier', type = 'Wind-based', trait = 'Resist Gravity (4)' , mob_family = 'Rocs' },
    { level = 58, points = 3, name = 'Flying Hip Press', type = 'Wind-based', trait = 'Max HP Boost (4)' , mob_family = 'Bugbear' },
    { level = 58, points = 5, name = 'Light of Penance', type = 'Light-based', trait = 'Auto Refresh (3)' , mob_family = 'Tonberry' },
    { level = 58, points = 3, name = 'Magic Fruit', type = 'Light-based', trait = 'Resist Sleep (4)' , mob_family = 'Opo-opo' },
    { level = 60, points = 5, name = 'Death Scissors', type = 'Slashing', trait = 'Attack Bonus (4)' , mob_family = 'Scorpion' },
    { level = 60, points = 5, name = 'Dimensional Death', type = 'Hand-to-Hand', trait = 'Accuracy Bonus (4)' , mob_family = 'Shadow' },
    { level = 61, points = 5, name = 'Bad Breath', type = 'Earth-based', trait = 'Fast Cast (4)' , mob_family = 'Morbol' },
    { level = 61, points = 4, name = 'Eyes On Me', type = 'Dark-based', trait = 'Magic Atk. Bonus (4)' , mob_family = 'Ahriman' },
    { level = 61, points = 5, name = 'Maelstrom', type = 'Water-based', trait = 'Clear Mind (4)' , mob_family = 'Sea Monk' },
    { level = 62, points = 5, name = '1000 Needles', type = 'Light-based', trait = 'Beast Killer (4)' , mob_family = 'Sabtotender' },
    { level = 62, points = 4, name = 'Body Slam', type = 'Blunt', trait = 'Max HP Boost (4)' , mob_family = 'Dragon' },
    { level = 62, points = 4, name = 'Memento Mori', type = 'Ice-based', trait = 'Magic Atk. Bonus (4)' , mob_family = 'Corse' },
    { level = 63, points = 3, name = 'Frenetic Rip', type = 'Blunt', trait = 'Accuracy Bonus (4)' , mob_family = 'Imps' },
    { level = 63, points = 3, name = 'Frypan', type = 'Blunt', trait = 'Max HP Boost (4)' , mob_family = 'Goblin/Moblin' },
    { level = 63, points = 3, name = 'Hydro Shot', type = 'Hand-to-Hand', trait = 'Rapid Shot (4)' , mob_family = 'Sahagin' },
    { level = 63, points = 4, name = 'Spinal Cleave', type = 'Slashing', trait = 'Attack Bonus (4)' , mob_family = 'Qutrub' },
    { level = 64, points = 3, name = 'Feather Tickle', type = 'Wind-based', trait = 'Clear Mind (4)' , mob_family = 'Colibri' },
    { level = 64, points = 4, name = 'Voracious Trunk', type = 'Wind-based', trait = 'Auto Refresh (3)' , mob_family = 'Marid' },
    { level = 64, points = 3, name = 'Yawn', type = 'Light-based', trait = 'Resist Sleep (4)' , mob_family = 'Apkallu' },
    { level = 65, points = 4, name = 'Infrasonics', type = 'Ice-based', trait = 'Magic Acc. Bonus (4)' , mob_family = 'Lizard' },
    { level = 65, points = 2, name = 'Zephyr Mantle', type = 'Wind-based', trait = 'Conserve MP (4)' , mob_family = 'Puk' },
    { level = 66, points = 4, name = 'Frost Breath', type = 'Ice-based', trait = 'Conserve MP (8)' , mob_family = 'Raptor' },
    { level = 66, points = 2, name = 'Sandspray', type = 'Dark-based', trait = 'Clear Mind (4)' , mob_family = 'Qiqirn' },
    { level = 67, points = 3, name = 'Diamondhide', type = 'Earth-based', trait = 'None' , mob_family = 'Troll' },
    { level = 67, points = 5, name = 'Enervation', type = 'Dark-based', trait = 'Counter (4)' , mob_family = 'Troll' },
    { level = 68, points = 5, name = 'Firespit', type = 'Fire-based', trait = 'Conserve MP (4)' , mob_family = 'Mamool Ja' },
    { level = 68, points = 4, name = 'Warm-Up', type = 'Earth-based', trait = 'Clear Mind (4)' , mob_family = 'Mamool Ja' },
    { level = 69, points = 5, name = 'Hysteric Barrage', type = 'Hand-to-Hand', trait = 'Evasion Bonus (4)' , mob_family = 'Lamia' },
    { level = 69, points = 4, name = 'Tail Slap', type = 'Hand-to-Hand', trait = 'Store TP (4)' , mob_family = 'Merrow' },
    { level = 70, points = 3, name = 'Amplification', type = 'Water-based', trait = 'None' , mob_family = 'Flan' },
    { level = 70, points = 3, name = 'Cannonball', type = 'Hand-to-Hand', trait = 'None' , mob_family = 'Wamouracampa' },
    { level = 71, points = 4, name = 'Heat Breath', type = 'Fire-based', trait = 'Magic Atk. Bonus (4)' , mob_family = 'Manticore' },
    { level = 71, points = 2, name = 'Lowing', type = 'Fire-based', trait = 'Clear Mind (4)' , mob_family = 'Buffalo' },
    { level = 72, points = 5, name = 'Disseverment', type = 'Piercing', trait = 'Accuracy Bonus (4)' , mob_family = 'Aern' },
    { level = 72, points = 3, name = 'Saline Coat', type = 'Light-based', trait = 'Defense Bonus (4)' , mob_family = 'Xzomit' },
    { level = 73, points = 4, name = 'Mind Blast', type = 'Thunder-based', trait = 'Clear Mind (4)' , mob_family = 'Soulflayer' },
    { level = 73, points = 4, name = 'Ram Charge', type = 'Blunt', trait = 'Lizard Killer (4)' , mob_family = 'Ram' },
    { level = 73, points = 4, name = 'Temporal Shift', type = 'Thunder-based', trait = 'Attack Bonus (4)' , mob_family = 'Hpemde' },
    { level = 74, points = 4, name = 'Actinic Burst', type = 'Light-based', trait = 'Auto Refresh (4)' , mob_family = 'Ghrah' },
    { level = 74, points = 4, name = 'Magic Hammer', type = 'Light-based', trait = 'None' , mob_family = 'Poroggo' },
    { level = 74, points = 5, name = 'Reactor Cool', type = 'Ice-based', trait = 'Magic Def. Bonus (4)' , mob_family = 'Zdei' },
    { level = 75, points = 4, name = 'Exuviation', type = 'Fire-based', trait = 'Resist Sleep (4)' , mob_family = 'Wamoura' },
    { level = 75, points = 5, name = 'Plasma Charge', type = 'Thunder-based', trait = 'Auto Refresh (4)' , mob_family = 'Phuabo' },
    { level = 75, points = 3, name = 'Vertical Cleave', type = 'Slashing', trait = 'Defense Bonus (4)' , mob_family = 'Euvhi' },
}

return spells
